apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-comet-search
  namespace: outpost   
  labels:
    app: green-comet-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-comet-search
  template:
    metadata:
      labels:
        app: green-comet-search
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: comet-test
          image: ghcr.io/outpostlabs/comet-search:latest
          ports:
          - containerPort: 3000
            protocol: TCP
          imagePullPolicy: Always
          command: ["pnpm"]
          args: ["dev"]