name: release

on:
  push:
    branches:
      - main
      - deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: outpostlabs/comet-search
  IMAGE_TAG: latest-${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/cache
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ORG_REPO_TOKEN }}
